[package]
name = "tfhe-versions-test-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tfhe_0_6 = { git = "https://github.com/zama-ai/tfhe-rs.git", branch = "ns/0.6_with_versionize", features = ["shortint", "x86_64-unix"], package = "tfhe"}
tfhe-versionable = { git = "https://github.com/zama-ai/tfhe-rs.git", branch = "ns/0.6_with_versionize" }
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
ciborium = "0.2"
